---
- hosts: all
  become_method: runas
  become: true
  tasks:
  - name: Install IIS
    win_feature:
      name:
      - Web-Server
      - Web-Http-Redirect
      - Web-Net-Ext45
      - Web-Asp-Net45
      - Web-ISAPI-Ext
      - Web-ISAPI-Filter
      - NET-WCF-HTTP-Activation45
      state: present
      include_sub_features: no
      include_management_tools: yes

  - name: Multipath IO
    win_feature:
      name: Multipath-IO
      state: present

  - name: Enable iSCSI initiator
    win_service:
      name: msiscsi
      state: started
      start_mode: auto
