---
- hosts: all
  become: true
  tasks:
  - name: Disable DHCP for eth0 
    lineinfile:
      path: /etc/netplan/01-netcfg.yaml
      regexp: 'dhcp4: true'
      state: absent

  - name: Define static IP address
    blockinfile:
      path: /etc/netplan/01-netcfg.yaml
      insertafter: 'eth0:'
      block: |6
            addresses:
                - {{ node_ip }}/24
            gateway4: {{ gateway_ip }}
            nameservers:
                search: [lab.local, englab.local]
                addresses: [{{ gateway_ip }}]

  - name: Remove boot delay
    lineinfile:
      path: /etc/default/grub
      insertafter: EOF
      line: GRUB_RECORDFAIL_TIMEOUT=5

  - name: Update grub
    command: update-grub

  - name: Enable Huge Page Support
    lineinfile:
      path: /etc/sysctl.conf
      line: vm.nr_hugepages = 512
      create: yes

  - name: Load required modules
    blockinfile:
      path: /etc/modules-load.d/mayastor.conf
      create: yes
      owner: root
      group: root
      mode: '0644'
      block: |
        nvme-tcp
        xfs
