kind: Pod
apiVersion: v1
metadata:
  name: fio
spec:
  # Run on a storage node so that the nexus is local to the app
  volumes:
    - name: ms-volume
      persistentVolumeClaim:
       claimName: pvc-1
  containers:
    - name: fio
      image: mayadata/fio
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/volume"
          name: ms-volume
